version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-jupyter-container
    ports:
      - 8888:8888
    volumes:
      - /Users/mikeldiez/docker-things/jupyterenv:/app
    environment:
      - JUPYTER_PASSWORD=default
